### ISSUE TITLE
Failed to download model

### ISSUE THREAD

**Issue by software-trizzey** [ariym/whisper-node#1]
Hi there, thanks for making these node bindings!

## Problem:

I was trying to add your project to mine and ran into an error after attempting to download the whisper model.

Using the command you provided, I got the following error:

```shell
npx whisper-node download-model base.en
npm ERR! could not determine executable to run
```

## Steps used to recreate the error:
I followed the project's README.md

Install the npm package:
```shell
npm i whisper-node

up to date, audited 230 packages in 440ms

44 packages are looking for funding
  run `npm fund` for details
```

Download the model:
```shell
npx whisper-node download-model base.en
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2023-03-12T17_22_13_443Z-debug-0.log
```

**Comment by irisrumtub** [comment]
Same here.

**Comment by ringge** [comment]
Same issue, so I digged into the module's code and found the reason
the download-model.sh was trying to "cd" into ./lib/whisper/models whereas the correct link is ./lib/whisper.app/models

**Comment by yashprovis** [comment]
> Same issue, so I digged into the module's code and found the reason the download-model.sh was trying to "cd" into ./lib/whisper/models whereas the correct link is ./lib/whisper.app/models

@ringge  Are you sure this is working?? I tried changing to ./lib/whisper.app/models but it says: 
sh: 1: download-model: not found

**Comment by ringge** [comment]
You're right, Go to node_modules/whisper-node/dist and then in shell.js you'll see the WHISPER_CPP_PATH is wrong, it needs to be fixed from here to make it work.

**Comment by yashprovis** [comment]
@ringge  Have you fixed the path? If yes, can you share the changes that are to be made in both download-model.sh & shell.js?

**Comment by dzlandis** [comment]
For now, you can go to the `./lib/whisper.cpp/models` and then run the `./download-ggml-model.cmd` or `./download-ggml-model.sh` to manually download a model. But I'm not quite sure the rest of the stuff working either.

**Comment by espinosakev24** [comment]
then to run the make file you would have to do "cd .." but even after running the makefile I'm getting errors :/

**Comment by ariym** [comment]
> Same issue, so I digged into the module's code and found the reason the download-model.sh was trying to "cd" into ./lib/whisper/models whereas the correct link is ./lib/whisper.app/models

It's actually .cpp, not .app but thank you for finding it was a path problem.

**Comment by ariym** [comment]
Issue has been resolved. Path has been corrected.
