### ISSUE TITLE
Problem: libc++abi: terminating due to uncaught exception of type std::invalid_argument: stoi: no conversion

### ISSUE THREAD

**Issue by changyongyong** [ariym/whisper-node#10]
[whisper-node] Problem: libc++abi: terminating due to uncaught exception of type std::invalid_argument: stoi: no conversion

**Comment by edoardocavazza** [comment]
Hi @changyongyong, did you found a solution for this issue?

**Comment by mefuru** [comment]
Any luck @edoardocavazza ?

**Comment by edoardocavazza** [comment]
Nope, I ended up using the OpenAI api.

**Comment by ariym** [comment]
The issue was in src/whisper.ts when the option 'timestamp_size' was used (as included in the README) dude to a mispelling as 'timestamp-size. The issue being a hypen - instead of an underscore _.
