### ISSUE TITLE
error: failed to open 'test.wav' as WAV file

### ISSUE THREAD

**Issue by ChetanXpro** [ariym/whisper-node#17]
I got other bugs also in which it was failing to download models , do i did those steps manually , and placed it in node modules , but now i am facing this error 

[whisper-node] Problem: whisper_init_from_file: loading model from './models/ggml-tiny.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 1
whisper_model_load: adding 1607 extra tokens
whisper_model_load: mem_required  =  390.00 MB
whisper_model_load: ggml ctx size =   73.58 MB
whisper_model_load: memory size   =   11.41 MB
whisper_model_load: model size    =   73.54 MB
error: failed to open 'test.wav' as WAV file

**Comment by ChetanXpro** [comment]
update: fixed mostly all bugs which are in issues , like model not downloading , and model not loading , and then failed to open 'test.wav' as WAV file bug

will raise a pr for all these changes

**Comment by HidanZZ** [comment]
Could you please tell me how did you fix the failed to open 'test.wav' as WAV file bug, please.

**Comment by ChetanXpro** [comment]
> Could you please tell me how did you fix the failed to open 'test.wav' as WAV file bug, please.

we have to convert file to wav ,but it's really annoying if we convert these manually, I created another package ,in which mostly all bugs are fixed, it will also convert file type automatically, you can check that
https://www.npmjs.com/package/nodejs-whisper
