### ISSUE TITLE
Stream and live recognition

### ISSUE THREAD

**Issue by ramiel** [ariym/whisper-node#22]
Hello. First of all thanks for this awesome project, it's what I was looking for.

I'm going to ask two questions.

- Is it possible to pass an audio stream instead of a file name? 
- Is it possible to do live stream recognition similar to what they do in the [original cpp version](https://github.com/ggerganov/whisper.cpp#real-time-audio-input-example)?
- 
Of course the first question is linked to the second, as you can undersand

**Comment by ariym** [comment]
Thank you! As of right now it this wrapper only makes use of whisper.cpp/main which is what takes in file but I am going to implement this in the next update.
