### ISSUE TITLE
I am getting this error when trying to download

### ISSUE THREAD

**Issue by anjalipandith** [ariym/whisper-node#24]
Hi Team

I am getting following error
vij@DESKTOP-8J00BG1 MINGW64 /f/test/Extra
$ npx whisper-node download

| Model     | Disk   | RAM     |
|-----------|--------|---------|
| tiny      |  75 MB | ~390 MB |
| tiny.en   |  75 MB | ~390 MB |
| base      | 142 MB | ~500 MB |
| base.en   | 142 MB | ~500 MB |
| small     | 466 MB | ~1.0 GB |
| small.en  | 466 MB | ~1.0 GB |
| medium    | 1.5 GB | ~2.6 GB |
| medium.en | 1.5 GB | ~2.6 GB |
| large-v1  | 2.9 GB | ~4.7 GB |
| large     | 2.9 GB | ~4.7 GB |

[whisper-node] Enter model name (e.g. 'base.en') or 'cancel' to exit
(ENTER for base.en):
[whisper-node] Going with base.en
Downloading ggml model base.en...
Model base.en already exists. Skipping download.
[whisper-node] Attempting to compile model...
'make' is not recognized as an internal or external command,
operable program or batch file.

Let me know how to fix this

Thanks

**Comment by ariym** [comment]
Assuming you're using Windows; after the model is downloaded whisper-node runs the **make** command to compile. This command is not included by default on Windows, [try this guide to install it](https://gnuwin32.sourceforge.net/packages/make.htm).
