### ISSUE TITLE
Is this support zh-cn ？out put is []

### ISSUE THREAD

**Issue by coderzzp** [ariym/whisper-node#25]
mycode:
```js
import {whisper} from 'whisper-node';

console.log('whisper',whisper)
const transcript = await whisper("./mycloning.wav");

console.log(transcript); 
```
why the output is []，not support chinese or need option？

![image](https://github.com/ariym/whisper-node/assets/24691802/6f49281d-943b-466c-bb58-241f2811a783)

**Comment by coderzzp** [comment]
replace with english wav not working also，what shoul i do

**Comment by ghost** [comment]
Me neither. It doesn't work even though I try to transcribe with base.en and tiny.en.

**Comment by ariym** [comment]
> Me neither. It doesn't work even though I try to transcribe with base.en and tiny.en.

base.en and tiny.en are optimized for English (hence the .en)

**Comment by ariym** [comment]
I added added the language option today in whisper-node@v1.1.1 but it expects 'chinese' instead of 'zh-cn'

You may also use the 'auto' option and it will detect which language.
