### ISSUE TITLE
Attempting to compile model error

### ISSUE THREAD

**Issue by coderzzp** [ariym/whisper-node#27]
i download the base.en model and success，but complied error 
![image](https://github.com/ariym/whisper-node/assets/24691802/4d8e4833-19d5-4b69-9273-98ef16346528)

**Comment by coderzzp** [comment]
my device is macos

**Comment by ariym** [comment]
I found a thread with a similar problem, [whisper.cpp issue 597](https://github.com/ggerganov/whisper.cpp/issues/597)

creator suggests removing the following lines from **lib/whisper.cpp/Makefile** 
```Makefile
139: CFLAGS   += -mf16c
140: CXXFLAGS += -mf16c
```
then run `make clean` + `make` and  see if that works.
