### ISSUE TITLE
Whisper-Node Make Fails at Runtime

### ISSUE THREAD

**Issue by dzlandis** [ariym/whisper-node#3]
I get the following error at start:
```
[whisper-node] Problem. whisper.pp not initialized. Current shelljs directory:  C:\Project\node_modules\whisper-node\dist
[whisper-node] Attempting to run 'make' command in /whisper directory...
[whisper-node] Problem. 'make' command failed. Please run 'make' command in /whisper directory. Current shelljs directory:  C:\Project\node_modules\whisper-node\dist
```

**Comment by styler2go** [comment]
Same here. Any solutions for windows?

**Comment by onexdata** [comment]
I've had the same problem for 3 weeks now. It looks like downloading models doesn't work either. Is this repo a WIP and doesn't work or?

**Comment by styler2go** [comment]
It seems like. I've decided to just get the whisper build from the repo and then use it like
```javascript
import {execFile as exec} from "child_process";

    transcribe(file): Promise<string> {
        return new Promise((resolve, reject) => {
            exec('lib/main.exe', ['--model', 'lib/ggml-base.bin', '-l', 'auto', '--file', file, '-otxt'], function (err, data) {
                if (!err) {
                    const output = fs.readFileSync(file + '.txt', {encoding: 'utf8'});
                    fs.unlinkSync(file + '.txt')
                    resolve(output);
                }

                reject(err);
            });
        });
    }
```
1. Get a build from https://github.com/ggerganov/whisper.cpp/releases
2. Get a model from https://huggingface.co/datasets/ggerganov/whisper.cpp/tree/main

And my lib folder then looks like:
![image](https://user-images.githubusercontent.com/2152144/232596085-b881755f-8c26-4637-9544-164d9c04322c.png)

**Comment by ariym** [comment]
> I get the following error at start:
> 
> ```
> [whisper-node] Problem. whisper.pp not initialized. Current shelljs directory:  C:\Project\node_modules\whisper-node\dist
> [whisper-node] Attempting to run 'make' command in /whisper directory...
> [whisper-node] Problem. 'make' command failed. Please run 'make' command in /whisper directory. Current shelljs directory:  C:\Project\node_modules\whisper-node\dist
> ```

Downloader had an incorrect path which has been corrected in 0.2 package update. Issue resolved.

**Comment by irisrumtub** [comment]
Same problem, using version 0.2.11

**Comment by KingCh1ll** [comment]
Same issue here.
