### ISSUE TITLE
ERROR INSTALL (npx whisper-node download)

### ISSUE THREAD

**Issue by LucianoAPP** [ariym/whisper-node#30]
[whisper-node] Enter model name (e.g. 'base.en') or 'cancel' to exit
(ENTER for base.en): 
[whisper-node] Going with base.en
Downloading ggml model base.en...
Model base.en already exists. Skipping download.
[whisper-node] Attempting to compile model...
"cc" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"head" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
I whisper.cpp build info:
I UNAME_S:
I UNAME_P:
I UNAME_M:
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -pthread
I LDFLAGS:
I CC:
I CXX:

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread   -c ggml.c -o ggml.o
process_begin: CreateProcess(NULL, uname -s, ...) failed.
process_begin: CreateProcess(NULL, uname -p, ...) failed.
process_begin: CreateProcess(NULL, uname -m, ...) failed.
process_begin: CreateProcess(NULL, which nvcc, ...) failed.
Makefile:299: recipe for target 'ggml.o' failed
process_begin: CreateProcess(NULL, cc -I. -O3 -DNDEBUG -std=c11 -fPIC -D_XOPEN_SOURCE=600 -pthread -c ggml.c -o ggml.o, ...) failed.
make (e=2): El sistema no puede encontrar el archivo especificado.
make: *** [ggml.o] Error 2

**Comment by ariym** [comment]
Which operating system are you using?

**Comment by LucianoAPP** [comment]
Windows 11 Home Single Language @ariym

**Comment by ariym** [comment]
[install this](https://gnuwin32.sourceforge.net/packages/make.htm) and then delete ```node_modules``` and try again

**Comment by LucianoAPP** [comment]
@ariymI installed this is it the same? https://sourceforge.net/projects/mingw/
